"""
Template 1: Static Audio - Editing Module

Audio & Video Editing for the Static Audio template.

- Step 1: Verify audio files (generated by Phase 3 Qwen3-TTS)
- Step 2: Generate scene videos (scene image + scene audio)
- Step 3: Create per-chapter videos → concatenate into final video
"""

import json
import time
import subprocess
import argparse
import sys
from collections import defaultdict
from pathlib import Path
from datetime import datetime

# Get ffmpeg path from imageio-ffmpeg
try:
    import imageio_ffmpeg
    FFMPEG_PATH = imageio_ffmpeg.get_ffmpeg_exe()
    FFMPEG_AVAILABLE = True
except ImportError:
    FFMPEG_PATH = None
    FFMPEG_AVAILABLE = False

# Add parent to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))

from src.config import COMFYUI_OUTPUT_DIR
from src.templates.base_template import EditingResult


def load_codex(codex_path: Path) -> dict:
    """Load codex JSON file."""
    with open(codex_path, "r", encoding="utf-8") as f:
        return json.load(f)


def save_codex(codex: dict, codex_path: Path) -> None:
    """Save codex JSON file."""
    with open(codex_path, "w", encoding="utf-8") as f:
        json.dump(codex, f, indent=2, ensure_ascii=False)


def get_audio_duration(audio_path: Path) -> float:
    """Get duration of audio file in seconds using ffprobe."""
    if not FFMPEG_AVAILABLE or not audio_path.exists():
        return 0.0

    try:
        result = subprocess.run(
            [FFMPEG_PATH, "-i", str(audio_path), "-f", "null", "-"],
            capture_output=True,
            text=True,
            timeout=30,
        )
        import re
        duration_match = re.search(r"Duration: (\d+):(\d+):(\d+)\.(\d+)", result.stderr)
        if duration_match:
            hours, mins, secs, ms = duration_match.groups()
            return int(hours) * 3600 + int(mins) * 60 + int(secs) + int(ms) / 100
    except Exception:
        pass
    return 0.0


def format_duration(seconds: float) -> str:
    """Format duration as MM:SS."""
    minutes = int(seconds // 60)
    secs = int(seconds % 60)
    return f"{minutes}:{secs:02d}"


def create_static_clip(
    image_path: Path,
    audio_path: Path,
    output_path: Path,
) -> tuple[bool, float]:
    """
    Create video clip from a static image with audio using ffmpeg directly.

    Uses ffmpeg -loop 1 to loop the image for the audio duration,
    matching E3's proven approach (no MoviePy frame buffer issues).

    Args:
        image_path: Path to the source image
        audio_path: Path to the audio file
        output_path: Path for the output video

    Returns:
        (success, duration)
    """
    if not FFMPEG_AVAILABLE:
        print("        ERROR: ffmpeg not available")
        return False, 0.0

    try:
        output_path.parent.mkdir(parents=True, exist_ok=True)

        result = subprocess.run(
            [
                FFMPEG_PATH,
                "-y",
                "-loop", "1",
                "-i", str(image_path),
                "-i", str(audio_path),
                "-c:v", "h264_nvenc",
                "-preset", "p4",
                "-pix_fmt", "yuv420p",
                "-c:a", "aac",
                "-b:a", "192k",
                "-shortest",
                "-movflags", "+faststart",
                str(output_path),
            ],
            capture_output=True,
            text=True,
            timeout=120,
        )

        if result.returncode != 0:
            print(f"        ERROR: ffmpeg failed: {result.stderr[-200:]}")
            return False, 0.0

        duration = get_audio_duration(audio_path)
        return True, duration

    except Exception as e:
        print(f"        ERROR: {e}")
        return False, 0.0


def _concatenate_clips(clip_paths: list[Path], output_path: Path) -> float:
    """Concatenate video clips using ffmpeg concat demuxer (no re-encoding).

    Args:
        clip_paths: Ordered list of video clip paths to concatenate.
        output_path: Destination path for the concatenated video.

    Returns:
        Total duration in seconds.
    """
    import tempfile

    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Write concat list file
    with tempfile.NamedTemporaryFile(mode="w", suffix=".txt", delete=False) as f:
        for p in clip_paths:
            f.write(f"file '{p.resolve()}'\n")
        list_file = f.name

    try:
        result = subprocess.run(
            [
                FFMPEG_PATH,
                "-y",
                "-f", "concat",
                "-safe", "0",
                "-i", list_file,
                "-c", "copy",
                "-movflags", "+faststart",
                str(output_path),
            ],
            capture_output=True,
            text=True,
            timeout=300,
        )

        if result.returncode != 0:
            raise RuntimeError(f"ffmpeg concat failed: {result.stderr[-300:]}")

        total = sum(get_audio_duration(p) for p in clip_paths)
        return total
    finally:
        Path(list_file).unlink(missing_ok=True)


def run_template1_editing(
    codex_path: Path,
    steps: list[int] = None,
    comfyui_output_dir: str = None,
) -> EditingResult:
    """
    Run Template 1 Editing: Audio & Video Editing.

    Steps:
        1: Verify audio files (generated by Phase 3 Qwen3-TTS)
        2: Generate scene videos (image + audio)
        3: Concatenate scene videos → final video

    Args:
        codex_path: Path to codex JSON file
        steps: List of steps to run (default: [1, 2, 3])
        comfyui_output_dir: ComfyUI output directory (default: from config)

    Returns:
        EditingResult with success status and output paths
    """
    steps_to_run = steps or [1, 2, 3]

    print(f"\n{'='*60}")
    print("TEMPLATE 1: Audio & Video Editing (Static Audio)")
    print(f"{'='*60}")
    print(f">>> Steps to run: {steps_to_run}")

    # Check ffmpeg availability
    if not FFMPEG_AVAILABLE:
        return EditingResult(
            codex_path=codex_path,
            scene_audio_count=0,
            scene_video_count=0,
            video_output_path=None,
            video_duration=0,
            success=False,
            error="ffmpeg not available. Install imageio-ffmpeg.",
        )

    print(f">>> Using ffmpeg: {FFMPEG_PATH}")

    # Load codex
    codex_path = Path(codex_path)
    if not codex_path.exists():
        return EditingResult(
            codex_path=codex_path,
            scene_audio_count=0,
            scene_video_count=0,
            video_output_path=None,
            video_duration=0,
            success=False,
            error=f"Codex not found: {codex_path}",
        )

    codex = load_codex(codex_path)

    # Get ComfyUI output directory
    if comfyui_output_dir is None:
        comfyui_output_dir = COMFYUI_OUTPUT_DIR

    # Output directories in forge
    forge_dir = codex_path.parent
    audio_dir = forge_dir / "audio"

    # Initialize counters
    scene_audio_count = 0

    # Initialize metadata in new structure
    if "metadata" not in codex:
        codex["metadata"] = {}
    phase4_metadata = {
        "started_at": datetime.now().isoformat(),
        "steps_executed": [],
        "template": "static_audio",
    }

    # Step timing
    step_timings = {}

    chapters_data = codex.get("story", {}).get("chapters", {})
    chapters = chapters_data.get("chapters", [])

    # Helper function to get scene image path
    def get_scene_image_path(ch_num: int, sc_num: int) -> Path | None:
        """Get scene image path from chapter/scene numbers."""
        for chapter in chapters:
            if chapter.get("chapter_number") == ch_num:
                for scene in chapter.get("scenes", []):
                    if scene.get("scene_number") == sc_num:
                        gen_data = scene.get("scene_image_prompt", {}).get("generation", {})
                        rel_path = gen_data.get("output_path", "")
                        if rel_path:
                            return Path(comfyui_output_dir) / rel_path
        return None

    def get_chapter_card_image_path(ch_num: int) -> Path | None:
        """Get chapter title card image path from chapter number."""
        for chapter in chapters:
            if chapter.get("chapter_number") == ch_num:
                gen_data = chapter.get("chapter_title_card", {}).get("generation", {})
                out_path = gen_data.get("output_path", "")
                if out_path:
                    p = Path(out_path)
                    return p if p.exists() else None
        return None

    # =========================================================================
    # Step 1: Verify Audio Files (generated by Phase 3 Qwen3-TTS)
    # =========================================================================
    if 1 in steps_to_run:
        step_start = time.time()
        print(f"\n{'='*60}")
        print("STEP 1: Verify Audio Files")
        print(f"{'='*60}")

        audio_gen_data = chapters_data.get("audio_generation", {})
        audio_items = audio_gen_data.get("items", [])

        if not audio_items:
            print(">>> No audio items found in chapters.audio_generation.items")
            print(">>> Run Phase 3 Step 5 (audio generation) first")
        else:
            completed = [i for i in audio_items if i.get("status") == "completed"]
            missing = 0
            verified = 0

            for item in completed:
                audio_path = Path(item.get("output_path", ""))
                if audio_path.exists():
                    verified += 1
                else:
                    missing += 1
                    print(f"    MISSING: {audio_path}")

            print(f">>> Audio items found: {len(audio_items)}")
            print(f">>> Completed: {len(completed)}")
            print(f">>> Verified on disk: {verified}")
            if missing:
                print(f">>> Missing files: {missing}")

            # Count by type
            titles = len([i for i in completed if i.get("type") == "title"])
            ch_titles = len([i for i in completed if i.get("type") == "chapter_title"])
            scenes = len([i for i in completed if i.get("type") == "scene"])
            print(f"    - Book titles: {titles}")
            print(f"    - Chapter titles: {ch_titles}")
            print(f"    - Scenes: {scenes}")

            scene_audio_count = verified

        phase4_metadata["steps_executed"].append(1)
        phase4_metadata["audio_items_count"] = len(audio_items) if audio_items else 0
        step_timings["step1_verify_audio"] = round(time.time() - step_start, 2)

        print(f"\n>>> Step 1 complete ({step_timings['step1_verify_audio']:.1f}s)")

    # =========================================================================
    # Step 2: Generate Video Clips (Audio + Matched Images)
    # =========================================================================
    scene_video_count = 0
    if 2 in steps_to_run:
        step_start = time.time()
        print(f"\n{'='*60}")
        print("STEP 2: Generate Video Clips")
        print(f"{'='*60}")

        if not FFMPEG_AVAILABLE:
            print(">>> ERROR: ffmpeg not available. Install imageio-ffmpeg.")
        else:
            # Reload codex in case Step 1 was run in a previous invocation
            codex = load_codex(codex_path)
            chapters_data = codex.get("story", {}).get("chapters", {})
            chapters = chapters_data.get("chapters", [])

            videos_dir = forge_dir / "videos"
            videos_dir.mkdir(parents=True, exist_ok=True)

            audio_items = chapters_data.get("audio_generation", {}).get("items", [])
            completed_items = [i for i in audio_items if i.get("status") == "completed"]

            if not completed_items:
                print(">>> No completed audio items found")
            else:
                # Sort by sequence number
                completed_items = sorted(completed_items, key=lambda x: x.get("sequence", 0))

                print(f">>> Creating {len(completed_items)} video clips...")
                print(f">>> Image matching:")
                print(f"    - title → Chapter 1, Scene 1 image")
                print(f"    - chapter_title → That chapter's Scene 1 image")
                print(f"    - scene → That scene's image")

                for item in completed_items:
                    seq = item.get("sequence", 0)
                    item_type = item.get("type", "unknown")
                    ch_num = item.get("chapter_number", 1)
                    sc_num = item.get("scene_number", 1)

                    # Get audio path (absolute path from Phase 3 TTS generation)
                    audio_path_str = item.get("output_path", "")
                    if not audio_path_str:
                        print(f"    [{seq}] {item_type} - No audio path, skipping")
                        continue

                    audio_path = Path(audio_path_str)
                    if not audio_path.exists():
                        print(f"    [{seq}] {item_type} - Audio file not found: {audio_path}")
                        continue

                    # Get matching image based on type
                    if item_type == "title":
                        # Book title → Chapter 1, Scene 1 image
                        image_path = get_scene_image_path(1, 1)
                        label = "Book Title"
                    elif item_type == "chapter_title":
                        # Chapter title → dedicated chapter title card, fallback to first scene image
                        image_path = get_chapter_card_image_path(ch_num)
                        if image_path is None:
                            # Fallback: use that chapter's first scene image
                            first_sc = next(
                                (ch["scenes"][0]["scene_number"]
                                 for ch in chapters if ch["chapter_number"] == ch_num and ch.get("scenes")),
                                None,
                            )
                            image_path = get_scene_image_path(ch_num, first_sc) if first_sc else None
                        label = f"Ch{ch_num} Title"
                    else:  # scene
                        # Scene → That scene's image
                        image_path = get_scene_image_path(ch_num, sc_num)
                        label = f"Ch{ch_num} Sc{sc_num}"

                    if image_path is None or not image_path.exists():
                        print(f"    [{seq}] {label} - No image found, skipping")
                        continue

                    # Create video clip
                    output_path = videos_dir / f"{seq:03d}_{item_type}.mp4"
                    print(f"    [{seq}/{len(completed_items)}] {label}...")

                    success, duration = create_static_clip(
                        image_path, audio_path, output_path
                    )

                    if success:
                        item["video_path"] = str(output_path)
                        item["video_duration"] = duration
                        scene_video_count += 1
                        print(f"        -> {output_path.name} ({format_duration(duration)})")

            save_codex(codex, codex_path)
            phase4_metadata["steps_executed"].append(2)
            phase4_metadata["scene_video_count"] = scene_video_count
            step_timings["step2_video_clips"] = round(time.time() - step_start, 2)

            print(f"\n>>> Step 2 complete ({step_timings['step2_video_clips']:.1f}s): {scene_video_count} video clips created")

    # =========================================================================
    # Step 3: Create Chapter Videos + Final Video
    # =========================================================================
    video_output_path = None
    video_duration = 0.0
    if 3 in steps_to_run:
        step_start = time.time()
        print(f"\n{'='*60}")
        print("STEP 3: Create Chapter Videos + Final Video")
        print(f"{'='*60}")

        if not FFMPEG_AVAILABLE:
            print(">>> ERROR: ffmpeg not available. Install imageio-ffmpeg.")
        else:
            # Reload codex in case Steps 1-2 were run in previous invocations
            codex = load_codex(codex_path)
            chapters_data = codex.get("story", {}).get("chapters", {})

            # Collect video paths from audio items in sequence order
            audio_items = chapters_data.get("audio_generation", {}).get("items", [])
            completed_items = sorted(
                [i for i in audio_items if i.get("status") == "completed" and i.get("video_path")],
                key=lambda x: x.get("sequence", 0),
            )

            # Group clips by chapter, separate book title
            title_clip = None
            chapter_clips: dict[int, list[dict]] = defaultdict(list)

            for item in completed_items:
                path = Path(item["video_path"])
                if not path.exists():
                    continue
                if item.get("type") == "title":
                    title_clip = item
                else:
                    chapter_clips[item.get("chapter_number", 1)].append(item)

            if not chapter_clips:
                print(">>> No video clips found. Run Step 2 first.")
            else:
                videos_dir = forge_dir / "videos"

                # Prepend book title to chapter 1
                if title_clip and title_clip.get("video_path"):
                    ch1_key = min(chapter_clips.keys())
                    chapter_clips[ch1_key].insert(0, title_clip)

                # --- Pass 1: Create per-chapter videos ---
                chapter_video_paths: list[Path] = []
                chapter_video_meta: dict[int, str] = {}
                total_clip_count = 0

                print(f"\n  --- Pass 1: Chapter videos ({len(chapter_clips)} chapters) ---")
                for ch_num in sorted(chapter_clips.keys()):
                    clips = sorted(chapter_clips[ch_num], key=lambda x: x.get("sequence", 0))
                    clip_paths = [Path(c["video_path"]) for c in clips if Path(c["video_path"]).exists()]

                    if not clip_paths:
                        continue

                    ch_output = videos_dir / f"chapter_{ch_num:02d}.mp4"
                    try:
                        ch_duration = _concatenate_clips(clip_paths, ch_output)
                        chapter_video_paths.append(ch_output)
                        chapter_video_meta[ch_num] = str(ch_output)
                        total_clip_count += len(clip_paths)
                        print(f"    Chapter {ch_num}: {len(clip_paths)} clips → {ch_output.name} ({format_duration(ch_duration)})")
                    except Exception as e:
                        print(f"    Chapter {ch_num}: ERROR - {e}")

                # --- Pass 2: Concatenate chapter videos → final ---
                if chapter_video_paths:
                    output_path = forge_dir / "final_video.mp4"
                    print(f"\n  --- Pass 2: Final video ({len(chapter_video_paths)} chapter videos) ---")

                    try:
                        video_duration = _concatenate_clips(chapter_video_paths, output_path)
                        video_output_path = output_path

                        phase4_metadata["chapter_videos"] = chapter_video_meta
                        phase4_metadata["final_video"] = {
                            "path": str(output_path),
                            "duration": video_duration,
                            "duration_formatted": format_duration(video_duration),
                            "clip_count": total_clip_count,
                            "chapter_count": len(chapter_video_paths),
                        }

                        print(f"    -> {output_path.name} ({format_duration(video_duration)})")
                        print(f"    File size: {output_path.stat().st_size / (1024*1024):.1f} MB")
                    except Exception as e:
                        print(f">>> ERROR creating final video: {e}")

        step_timings["step3_final_video"] = round(time.time() - step_start, 2)
        phase4_metadata["steps_executed"].append(3)
        print(f"\n>>> Step 3 complete ({step_timings['step3_final_video']:.1f}s)")

    # Finalize metadata
    phase4_metadata["completed_at"] = datetime.now().isoformat()
    codex["metadata"]["phase_4"] = phase4_metadata
    save_codex(codex, codex_path)

    # Summary
    print(f"\n{'='*60}")
    print("TEMPLATE 1 EDITING COMPLETE")
    print(f"{'='*60}")
    print(f">>> Scene audio files: {scene_audio_count}")
    print(f">>> Scene videos: {scene_video_count}")
    if video_output_path:
        print(f">>> Final video: {video_output_path}")
        print(f">>> Total duration: {format_duration(video_duration)}")

    return EditingResult(
        codex_path=codex_path,
        scene_audio_count=scene_audio_count,
        scene_video_count=scene_video_count,
        video_output_path=video_output_path,
        video_duration=video_duration,
        success=True,
        step_timings=step_timings,
    )


def main():
    """CLI entry point."""
    parser = argparse.ArgumentParser(
        description="Template 1: Audio & Video Editing (Static Audio)",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Steps:
  1: Verify audio files (from Phase 3 Qwen3-TTS)
  2: Generate scene videos (static image + audio)
  3: Concatenate scene videos -> final video

Examples:
  # Run all steps
  uv run python -m src.templates.template_1_static_audio.editing forge/20260116191326/codex_20260116191326.json

  # Run specific steps
  uv run python -m src.templates.template_1_static_audio.editing forge/20260116191326/codex_20260116191326.json --steps 1 2 3
        """
    )
    parser.add_argument("codex_path", help="Path to codex JSON file")
    parser.add_argument(
        "--steps",
        nargs="+",
        type=int,
        choices=[1, 2, 3],
        default=[1, 2, 3],
        help="Steps to run (default: 1 2 3)"
    )

    args = parser.parse_args()

    result = run_template1_editing(
        codex_path=Path(args.codex_path),
        steps=args.steps,
    )

    if result.success:
        print(f"\n>>> Template 1 Editing complete!")
        print(f"    Scene audio: {result.scene_audio_count}")
        print(f"    Scene videos: {result.scene_video_count}")
        if result.video_output_path:
            print(f"    Final video: {result.video_output_path}")
            print(f"    Duration: {format_duration(result.video_duration)}")
    else:
        print(f"\n>>> Template 1 Editing failed: {result.error}")
        sys.exit(1)


if __name__ == "__main__":
    main()
